#!/bin/bash

rm -rf hex/
mkdir -p hex
for SAMPLENAME in source/examples/*
do
    echo $SAMPLENAME
    rm source/*.cpp 2> /dev/null
    cp -a $SAMPLENAME/*.cpp source
    if [[ -e $SAMPLENAME/config.json ]]
    then
        cp -a $SAMPLENAME/config.json .
    fi
    ls source
    yt clean
    yt build
    cp build/bbc-microbit-classic-gcc/source/microbit-samples-combined.hex hex/$(basename $SAMPLENAME).hex
done
